# Generated by Django 5.1.4 on 2024-12-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(max_length=5000, verbose_name='Image URL')),
                ('product_url', models.URLField(max_length=5000, verbose_name='Product URL')),
                ('name', models.CharField(max_length=555, verbose_name='Product Name')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Current Price')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Old Price')),
                ('discount', models.CharField(blank=True, max_length=50, null=True, verbose_name='Discount')),
                ('offer_end_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Offer End Date')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
