# Generated by Django 5.1.4 on 2024-12-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plastatyion_app', '0003_alter_product_offer_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Offer End Date'),
        ),
    ]
